from django.db import models

# Create your models here.
class home(models.Model):
    username = models.CharField(max_length=100)
    fullname = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    troom = models.CharField(max_length=100)
    tbal = models.CharField(max_length=100)
    tchimney = models.CharField(max_length=100)
    tsofa = models.CharField(max_length=100)
    tcarpet = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    address = models.TextField()
    ph1 = models.CharField(max_length=100)
    ph2 = models.CharField(max_length=100)
    otser = models.TextField(default='')
class rooms(models.Model):
    username = models.CharField(max_length=100)
    fullname = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    tfans = models.CharField(max_length=100)
    talmirah = models.CharField(max_length=100)
    tflooring = models.CharField(max_length=100)
    tarea = models.CharField(max_length=100)
    tcarpet = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    address = models.TextField()
    ph1 = models.CharField(max_length=100)
    ph2 = models.CharField(max_length=100)
    otser = models.TextField(default='')
class sofa(models.Model):
    username = models.CharField(max_length=100)
    fullname = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    tseats = models.CharField(max_length=100)
    tsofa = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    address = models.TextField()
    ph1 = models.CharField(max_length=100)
    ph2 = models.CharField(max_length=100)
    otser = models.TextField(default='')
class kitchen(models.Model):
    username = models.CharField(max_length=100)
    fullname = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    tcupboard = models.CharField(max_length=100)
    tchimney = models.CharField(max_length=100)
    tfridge = models.CharField(max_length=100)
    tro = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    address = models.TextField()
    ph1 = models.CharField(max_length=100)
    ph2 = models.CharField(max_length=100)
    otser = models.TextField(default='')
class bathroom(models.Model):
    username = models.CharField(max_length=100)
    fullname = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    tglass = models.CharField(max_length=100)
    tbuckets = models.CharField(max_length=100)
    ttubs = models.CharField(max_length=100)
    ttaps = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    address = models.TextField()
    ph1 = models.CharField(max_length=100)
    ph2 = models.CharField(max_length=100)
    otser = models.TextField(default='')
class toilet(models.Model):
    username = models.CharField(max_length=100)
    fullname = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    tglass = models.CharField(max_length=100)
    ttaps = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    address = models.TextField()
    ph1 = models.CharField(max_length=100)
    ph2 = models.CharField(max_length=100)
    otser = models.TextField(default='')
class carpet(models.Model):
    username = models.CharField(max_length=100)
    fullname = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    lcarpet = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    address = models.TextField()
    ph1 = models.CharField(max_length=100)
    ph2 = models.CharField(max_length=100)
    otser = models.TextField(default='')
class car(models.Model):
    username = models.CharField(max_length=100)
    fullname = models.CharField(max_length=500)
    email = models.CharField(max_length=100)
    ncar = models.CharField(max_length=100)
    wcar = models.CharField(max_length=100)
    tcar = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    address = models.TextField()
    ph1 = models.CharField(max_length=100)
    ph2 = models.CharField(max_length=100)
    otser = models.TextField(default='')
    